### ISSUE TITLE
Deprecated call to `systemGetProduct(long)` used in `searchService.checkIndex()`

### ISSUE THREAD

**Issue by sustr4** [SentinelDataHub/dhus-core#22]
Function `checkIndex()` uses variable `Long pid` as a parameter to calling `systemGetProduct()` here:

https://github.com/SentinelDataHub/dhus-core/blob/6ee5631c31991e99ae7c75de5b518d2d5f7e8182/core/src/main/java/fr/gael/dhus/service/SearchService.java#L308

In broader operational context it results into a _Warning_ log message being generated for **every** product held in the given DHuS instance on every run of the _systemCheck_ CRON job, e.g.:

`[2.7.7-osf][2021-04-27 23:30:00,016][WARN ] Call to deprecated method systemGetProduct(long), use systemGetProduct(String uuid) instead (ProductService.java:101 - jobScheduler_Worker-6)`

`checkIndex()` should be refactored to use the existing definition of `systemGetProduct(uuid)` here:
https://github.com/SentinelDataHub/dhus-core/blob/6ee5631c31991e99ae7c75de5b518d2d5f7e8182/core/src/main/java/fr/gael/dhus/service/ProductService.java#L140

Another occurrence of this deprecated call may also be found in `SearchService.asProduct` here:

https://github.com/SentinelDataHub/dhus-core/blob/6ee5631c31991e99ae7c75de5b518d2d5f7e8182/core/src/main/java/fr/gael/dhus/service/SearchService.java#L256

**Comment by nivalette** [comment]
Handled in future OSF release
